= ESB cloud stack

image::https://github.com/yupiik/esb/actions/workflows/maven.yml/badge.svg?branch=main[Github CI]

The purpose of this repository is to show how to build a custom ESB based on Apache Karaf & Apache Camel to be cloud friendly.

== Build

Prerequisite:

* Maven 3.x
* JDK 11

To build the project:

[source,shell script]
----
mvn clean install
----

The platform is available as a tar.gz and zip format in:

[source,shell script]
----
├── distribution
│   └── target
│       ├── esbcloud-distribution-1.0.0-SNAPSHOT.jar
│       ├── esbcloud-distribution-1.0.0-SNAPSHOT.tar.gz
│       ├── esbcloud-distribution-1.0.0-SNAPSHOT.zip

----

The main platform directory is:

[source,shell script]
----
├── distribution
│   └── target
│       ├── assembly
│       │   └── karaf
----

== Run

To run the platform in system out mode (for Docker):

[source,shell]
----
./distribution/target/assembly/karaf/bin/karaf run
----

To run the platform in shell console:

[source,shell]
----
./distribution/target/assembly/karaf/bin/karaf
----

To run the platform in background process:

[source,shell]
----
./distribution/target/assembly/karaf/bin/start
----

== Configuration

The following properties can be set with system environment variables:

[source,shellscript]
----
# Logging
LOG4J2_LOGGING_APPENDER_CONSOLE=Console
LOG4J2_LOGGING_PATTERN_CONSOLE={\"@timestamp\": \"%d{yyyy-MM-dd'T'HH:mm:ss.SSS}\", \"level\": \"%p\", \"logger\": \"%logger{63}:%L\", \"thread\": \"%t\", \"classname\": \"%class{63}\", \"message\": \"%encode{%m%wEx{full}}{JSON}\"}%n

# Kafka cluster notification
ESBCLOUD_KAFKA_BROKERS=localhost:9093
ESBCLOUD_KAFKA_TOPIC=dev.si.docawesome
ESBCLOUD_KAFKA_SECURITY_PROTOCOL=SASL_PLAINTEXT
ESBCLOUD_KAFKA_SECURITY_SASL_MECHANISM=SCRAM-SHA-512
ESBCLOUD_KAFKA_SECURITY_SASL_MODULE=org.apache.kafka.common.security.scram.ScramLoginModule
ESBCLOUD_KAFKA_SECURITY_SASL_USERNAME=esbcloud
ESBCLOUD_KAFKA_SECURITY_SASL_PASSWORD=changeit

# Expose api
ESBCLOUD_ENDPOINT_PROTOCOL=http
ESBCLOUD_ENDPOINT_HOST=localhost
ESBCLOUD_ENDPOINT_PORT=8080
ESBCLOUD_ENDPOINT_CXF_TRACE_ACTIVE=false

# API Gateway credentials for external poll
ESBCLOUD_POLL_CLIENT_USERNAME=esbcloud
ESBCLOUD_POLL_CLIENT_PASSWORD=changeit
----

When running the instance locally you can define the properties in

[source]
----
./distribution/target/assembly/karaf/bin/karaf/etc/io.yupiik.esbcloud.entrypoint.camelcontext.cfg
./distribution/target/assembly/karaf/bin/karaf/etc/io.yupiik.esbcloud.services.collect.camelcontext.cfg
----

Properties are loaded by Felix ConfigAdmin interpolate:

[source,properties]
----
# API published entrypoint
esbcloud.endpoint.host=$[env:ESBCLOUD_ENDPOINT_HOST=localhost]
esbcloud.endpoint.port=$[env:ESBCLOUD_ENDPOINT_PORT=8080]
esbcloud.endpoint.protocol=$[env:ESBCLOUD_ENDPOINT_PROTOCOL=http]
esbcloud.endpoint.cxf.trace.active==$[env:ESBCLOUD_ENDPOINT_CXF_TRACE_ACTIVE;default=false]
----

You can replace the default values.


== Docker

[source,xml]
----
<entrypoint>
    <entrypoint>/karaf/bin/karaf</entrypoint>
    <entrypoint>run</entrypoint>
</entrypoint>
<workingDirectory>/karaf</workingDirectory>
<permissions>
    <permission>
        <file>/karaf/bin/karaf</file> <!-- executable entrypoint -->
        <mode>755</mode>
    </permission>
</permissions>
----

Health check is available at `http://host:8080/status`

== Development

=== Debug

To debug code you have to run the distribution in debug mode:

[source,shell script]
----
./distribution/target/assembly/karaf/bin/karaf debug
----

Remote debug is now available on `localhost:5005`

Then you can activate the bundle refresh watching:

[source,shell]
----
karaf@root()> bundle:watch *
----

When building a maven module, it will be automatically reloaded in the running instance.
You don't need to build all the project.

Tail log:

[source,shell]
----
karaf@root()> log:tail
----

== Test

=== Send notification to jms

[source,shell]
----
curl -X 'POST' \
  'http://localhost:8080/notification' \
  -H 'accept: application/json;charset=utf-8' \
  -H 'X-Routing-System: jms' \
  -H 'Content-Type: application/json;charset=utf-8' \
  -d '{
  "reference": "INF161200001",
  "date": "01/01/1970 00:00:00",
  "message": "Update contract"
}'
----


=== Send notification to kafka

[source,shell]
----
curl -X 'POST' \
  'http://localhost:8080/notification' \
  -H 'accept: application/json;charset=utf-8' \
  -H 'X-Routing-System: kafka' \
  -H 'Content-Type: application/json;charset=utf-8' \
  -d '{
  "reference": "INF161200001",
  "date": "01/01/1970 00:00:00",
  "message": "Update contract"
}'
----

=== Send notification to unknown

[source,shell]
----
curl -X 'POST' \
  'https://localhost:8080/notification' \
  -H 'accept: application/json;charset=utf-8' \
  -H 'X-Routing-System: unknown' \
  -H 'Content-Type: application/json;charset=utf-8' \
  -d '{
  "reference": "INF161200001",
  "date": "01/01/1970 00:00:00",
  "message": "Update contract"
}'
----
