version: '3'

services:

  esbcloud-zookeeper:
    container_name: esbcloud-zookeeper
    image: confluentinc/cp-zookeeper:5.4.3
    ports:
      - 2181:2181
    volumes:
      - ./scripts/security:/etc/kafka/secrets
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/zookeeper_jaas.conf -Dzookeeper.authProvider.1=org.apache.zookeeper.server.auth.SASLAuthenticationProvider -Dzookeeper.requireClientAuthScheme=sasl"

  esbcloud-kafka:
    container_name: esbcloud-kafka
    image: confluentinc/cp-kafka:5.4.3
    depends_on:
      - esbcloud-zookeeper
    ports:
      - 9092:9092
      - 9093:9093
    volumes:
      - ./scripts/security:/etc/kafka/secrets
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: esbcloud-zookeeper:2181

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

      KAFKA_LOG4J_LOGGERS: "kafka.authorizer.logger=INFO"
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO

      KAFKA_DELETE_TOPIC_ENABLE: 'true'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_SUPER_USERS: User:admin;User:ANONYMOUS;User:yupiik

      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:SASL_PLAINTEXT

      KAFKA_LISTENERS: INTERNAL://esbcloud-kafka:9092,EXTERNAL://esbcloud-kafka:9093

      KAFKA_ADVERTISED_LISTENERS: INTERNAL://esbcloud-kafka:9092,EXTERNAL://esbcloud-kafka:9093

      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_AUTHORIZER_CLASS_NAME: "kafka.security.authorizer.AclAuthorizer"

      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: SCRAM-SHA-512
      KAFKA_SASL_ENABLED_MECHANISMS: SCRAM-SHA-512

      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/secrets/kafka_server_jaas.conf"

  #https://github.com/provectus/kafka-ui
  esbcloud-kafka-ui:
    image: provectuslabs/kafka-ui
    container_name: esbcloud-kafka-ui
    depends_on:
      - esbcloud-kafka
    ports:
      - 9080:8080
    environment:
      - KAFKA_CLUSTERS_0_NAME=local
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=esbcloud-kafka:9092
      - KAFKA_CLUSTERS_0_ZOOKEEPER=esbcloud-zookeeper:2181
